services:
  web:
    build: ./services/web
    volumes:
      - ./services/web/:/usr/src/app/
      - db_data:/home/app/data/
    ports:
      - "3888:3888"
    env_file:
      - ./.env.dev
networks: {}
volumes:
  db_data: